import { signIn, signOut, useSession } from "next-auth/react";
import Head from "next/head";
import WeekView from "../components/calendars/week_view";
import BorderlessStacked from "../components/calendars/borderless_stacked";
import MonthView from "../components/calendars/month_view";

import { api } from "~/utils/api";
import { redirect } from "next/navigation";
import { useEffect } from "react";

export default function Home() {
  const { data, status } = useSession();
  if (status == "unauthenticated") {
    signIn();
  }
  return (
    <>
      <Head>
        <title>Cornell Roster/Schduler</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        {JSON.stringify(data)}
        {/* <WeekView /> */}
        {/* <div className="w-80"><BorderlessStacked /></div> */}
        <MonthView />
      </main>
    </>
  );
}
