// the default when authenticated we show this header and footer
import { useSession } from "next-auth/react";
import Head from "next/head";
import React, { ReactNode } from "react";
import NavSimple from "./simple";
import Footer from "./4_column_with_newsletter_below";

function DefaultAuth({ children }: { children: ReactNode }) {
  const { data, status } = useSession();
  return (
    <>
      <Head>
        <title>Cornell Roster/Schduler</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <NavSimple />
        {children}
        {/* <Footer /> */}
      </main>
    </>
  );
}

export default DefaultAuth;
